### PR TITLE
Update track.py

### PR DESCRIPTION
**Pull request by carrie2780**
import strip_optimizer

### CODE REVIEW

**Comment by carrie2780** [comment]
import strip_optimizer

**Comment by mikel-brostrom** [comment]
Why a PR only for an import that is not used?

**Comment by hungnt14** [comment]
> Why a PR only for an import that is not used?

But we still have a flag to use it. Why don't we import it?

**Comment by mikel-brostrom** [comment]
I am doing a major refactor. All the new Yolov8 stuff is in there. Give me few more days. THis will be fixed as well :smile:

**Pull request closed without merging**
