### PR TITLE
refactor into config file + add more visualization and output option + yolov5 support

### PR DESCRIPTION
**Pull request by RiuCH**
- Modify track.py to input yaml config file instead of too many argparser. Also create function to set default value in case of unspecified value in the config file
- Modify the output result config option to be able to have config file and logging attached for easier experiment
- Add support for YOLOV5 model
- Add heatmap and human foot trailing visualization 
- If you consider this a good practice, I will further refactor the code in val.py / evolve.py and modify the README

### CODE REVIEW

**Comment by mikel-brostrom** [comment]
I agree that all the relevant parameters for the experiment should be saved in a single file. However many of the parameters doesn't seem to be so relevant, like:

```
device: "cpu"                                               # cuda device, i.e. 0 or 0,1,2,3 or cpu
save_txt: True                                              # save results to *.txt
save_config: True                                           # save configs to *.json
save_log: True                                              # save log & runtime to *.log      
save_trajectories: True                                     # save trajectories for each track
save_vid: True                                              # save video tracking results
show_vid: False                                             # visualize video while running
```

I don't see:

> Add heatmap and human foot trailing visualization

in the PR. This could be very interesting to have a look at :rocket:

**Comment by RiuCH** [comment]
For the 'device' param, I think it is relevant because you can track what device you use to run the experiment in case you want to test computing time. For the other vis param, it can be split into its own vis config file separated from core function param. Btw do you think

**Comment by RiuCH** [comment]
Im currently working on HM and human trail visualization on my other project. I may push the commit to PR later. I see that your current trajectories vis can only work with strongsort right?

**Comment by mikel-brostrom** [comment]
> I see that your current trajectories vis can only work with strongsort right?

Yes, that is currently the case

**Comment by RiuCH** [comment]
I already split the config parameter into two type. The trajectory vis can be used for all tracking algo. Btw heatmap vis is just background subtraction for now. I will implement later to get heatmap from segment result.

**Pull request closed without merging**
